# Mean Normalization(均值归一化)

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [1]:
# import NumPy into Python

import numpy as np
# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001,size=(1000,20))

# print the shape of X
print(X)

[[2253 2575 1472 ... 4806 1119 2754]
 [1748  962 3457 ... 3267  960 2260]
 [4329 1551 2572 ... 1815  828 1489]
 ...
 [1196 1345 4399 ... 3709 3927 2138]
 [4335 3278  881 ... 2639 2311  293]
 [1226 4313 1277 ... 3316  379 2423]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [4]:
# Average of the values in each column of X
ave_cols = X.mean(axis=0)

# Standard Deviation of the values in each column of X
std_cols =  X.std(axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [8]:
# Print the shape of ave_cols
print(ave_cols.shape)

# Print the shape of std_cols
print(std_cols.shape)

(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [6]:
# Mean normalize X
X_norm = (X - ave_cols)/std_cols

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [10]:
# Print the average of all the values of X_norm

print(X_norm)
# Print the average of the minimum value in each column of X_norm
print(X_norm.min(axis=0))

# Print the average of the maximum value in each column of X_norm
print(X_norm.max(axis=0))

[[-0.16726959  0.02858348 -0.70022186 ...  1.55130427 -0.9986985
   0.18959795]
 [-0.51551372 -1.07793143  0.65961049 ...  0.49778717 -1.11015006
  -0.14689593]
 [ 1.26432413 -0.67387856  0.05333763 ... -0.49617438 -1.20267588
  -0.6720716 ]
 ...
 [-0.8961687  -0.81519417  1.30493143 ...  0.80035673  0.9695781
  -0.22999766]
 [ 1.26846168  0.51084014 -1.10508882 ...  0.06789195 -0.16316228
  -1.486741  ]
 [-0.87548093  1.22084816 -0.83380741 ...  0.53132995 -1.51740387
  -0.03586657]]
[-1.71540441 -1.7351176  -1.70862147 -1.81124407 -1.74715433 -1.61814343
 -1.74983223 -1.78203616 -1.75745838 -1.67449184 -1.71740006 -1.72567905
 -1.65709523 -1.67669057 -1.83084701 -1.8206619  -1.75655157 -1.73725722
 -1.78096227 -1.68632138]
[1.72290304 1.69144285 1.71390872 1.72282302 1.77978825 1.7700504
 1.68537736 1.69843502 1.7442984  1.75366074 1.73158559 1.71852861
 1.68965356 1.78092919 1.72064064 1.71840152 1.72655113 1.68136811
 1.72099993 1.71744366]


You should note that since $X$ was created using random integers, the above values will vary. 

## Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. **This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets**.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [12]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([2, 1, 3, 0, 4])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [17]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row,col = X_norm.shape
row_indices = np.random.permutation(row)
# print(row_indices)

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [21]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.


# Create a Training Set
X_train = X_norm[row_indices[0:600]]

# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[600:800]]

# Create a Test Set
X_test = X_norm[row_indices[800:1000]]


If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [24]:
# Print the shape of X_train

print("X_train： ",X_train.shape)
# Print the shape of X_crossVal

print("X_crossVal： ",X_crossVal.shape)
# Print the shape of X_test
print("X_test: ",X_test.shape)

X_train：  (600, 20)
X_crossVal：  (200, 20)
X_test:  (200, 20)
